# Generated by Django 2.2.3 on 2019-09-15 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='capsule_create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
