# Generated by Django 2.0.13 on 2020-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
