# Generated by Django 2.0.13 on 2020-03-29 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0002_auto_20200229_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimage',
            field=models.ImageField(default='', upload_to='userimage/'),
        ),
        migrations.AddField(
            model_name='user',
            name='userlogintime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 13, 4, 12, 512964, tzinfo=utc)),
        ),
    ]
