# Generated by Django 2.0.13 on 2020-01-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0002_auto_20200112_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_create_time',
            new_name='usercreatetime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_nickname',
            new_name='usernickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='userpassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_sex',
            new_name='usersex',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_title',
            new_name='usertitle',
        ),
    ]
