# Generated by Django 2.2.3 on 2019-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0003_auto_20190915_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='capsule_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='capsule',
            name='capsule_image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='capsule',
            name='capsule_location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='capsule',
            name='capsule_person',
            field=models.TextField(default=''),
        ),
    ]
