# Generated by Django 2.0.13 on 2020-04-06 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0003_auto_20200329_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userlogintime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
