# Generated by Django 2.0.13 on 2020-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0004_auto_20200406_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userimage',
        ),
        migrations.AddField(
            model_name='user',
            name='userimg',
            field=models.ImageField(null=True, upload_to='userimage/'),
        ),
    ]
