# Generated by Django 2.2.3 on 2019-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0004_auto_20190928_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='capsule_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_type',
            field=models.TextField(default=''),
        ),
    ]
