# Generated by Django 2.2.3 on 2019-10-02 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0005_auto_20190928_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('user_password', models.CharField(max_length=256)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('user_create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
