# Generated by Django 2.2.3 on 2019-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0007_auto_20191116_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32),
        ),
    ]
