# Generated by Django 2.2.3 on 2019-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0009_auto_20191117_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32),
        ),
    ]
