# Generated by Django 2.2.3 on 2019-11-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorycapsuleservice', '0010_auto_20191117_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='capsule_date',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_image',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_location',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_person',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_time',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='capsule_type',
            field=models.CharField(default='', max_length=128),
        ),
    ]
